services:
  frontend:
    container_name: spring-app-frontend
    # image: spring-frontend:0.1
    build:
      context: ./product-management-frontend-app
      dockerfile: Dockerfile.compose
    environment:
      - REACT_APP_BASE_API=/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - spring-bridge
    depends_on:
      - api

  api:
    container_name: spring-app-api
    build: ./ProductManagementBackEndApp
    env_file: ./app.env
    networks:
      - spring-bridge
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: spring-app-mysql
    image: mysql:latest
    env_file: ./mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-bridge
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    container_name: spring-app-phpmyadmin
    image: phpmyadmin:latest
    env_file: ./phpmyadmin.env
    ports:
      - "8080:80"
    networks:
      - spring-bridge
    depends_on:
      - mysql

networks:
  spring-bridge:
    driver: bridge

volumes:
  mysql-data:
